### ISSUE TITLE
Namelists, DSSAT tips and test data.

### ISSUE THREAD

**Issue by jramarohetra** [RDCEP/psims#2]
Hello,

I am preparing pDSSAT installation and I prior to do so I have a few questions:
-   Concerning DSSAT installation:
    o Which version of DSSAT do you use (and is it important)? I cannot find a “make” executable on all of them. On the GitHub sometimes I see the name “46” (e.g. in “Compiling DSSAT” paragraph), sometimes I see “45” (e.g. in “Params file format” table). Did you synchronized it with DSSAT GitHub?  
    o Where should I copy DSSAT source code and compile it? Does it have an importance?
    o In which directory should I put the DSCSMO45.exe file? /bin directory? Or in /models/pdssat?
-   Concerning scenario template (and campaign files): does a namelist already exist?
-   Does a namelist exist for swift.properties file as well?
-   With which data could I test the results? Does a “test” dataset (including all input files and results) exist? Should I use the Midway cluster for a preliminary test? (by the way, the link to «More information about Midway» does not work anymore)

Many thanks,
Johanna

**Comment by DavidMichaelKelly** [comment]
Hi Johanna,
- Either 4.5 or 4.6 should work with psims. DSSAT is not typically built on Unix systems, which is why it doesn't include a Makefile. Running the patch command in the instructions will create a Makefile and make some minor modifications to the codebase to allow it to compile on Linux. I believe this patch was tested against 4.6. In order to obtain the DSSAT source, you must join the DSSAT group at https://github.com/DSSAT.
- Once DSSAT is compiled, the location doesn't matter too much, it just needs to be in your PATH.
- I'm not sure what you mean for a namelist for swift.properties, scenario, and campaigns?
- There isn't a public test dataset available to test inputs and outputs.

**Comment by jramarohetra** [comment]
Hi David,
Thanks for your replies!

• So if I understand well I won’t be able to compare the outputs I get to those you get, even using md5 checksums. I can check my results only comparing them to results I already have myself.

• Concerning the namelists: I just wondered if there is somewhere a file describing the variables/parameters set in these files (swift.properties, scenario, and campaigns). 

For example: if I want to add a site to run pSIMS I guess I would go to swift.properties file and add a site. But I don’t know how to set the options. They are obviously not the same for “local” ad “midway” sites. Which lines are necessary/optional?
Another example is with the campaign file: in the campaign file I can see there are 9 variables I can set (treatment name, irrigation, nitrogen, evaporation, start of planting window, end of planting window, cultivar id, N application at date 1, N application at date 2). If I want to make scenarios changing the soils. How should I do it? Should I change the campaign file only, adding a variable? How should I name this new variable for it to be recognized by the code?
And with the exp_template.json file: I don’t really understand all the abbreviations in this file.

So if what I call “namelists” are available that would help me a lot. If they are not I will do without them, it will just take longer (I hope).

• I have an extra question concerning the soil dataset (I am preparing them now and trying to figure out how to organize them). If I understand well, soil characteristics have to be ordered spatially (in the /soil_dataset/grid1/grid2 directories). 

What if I want to run pSIMS using different soils over one area? 
Can I do that using the campaign file (e.g.: one soil for scenario 1, another one for scenario 2)? Then how: Should I put more than one soil file in each /grid1/grid2/ directory (by the way, what happens if I do so)? 
Should I generate as many “soil datasets” as there are soils I want to test over one area? And then launch a new run for each “soil dataset” I have?

It seems to me that I will need to duplicate many soil files (and many directory). Is that the only way to deal with soils or is there a trick to avoid it? Can I put a symbolic link in the directories?

Thanks,
Johanna

**Comment by joshuaelliott** [comment]
the documentation that is on here is pretty much everything there is. the experiment files use the ICASA standards for variable names which you can find by googling or on the agmip site i think. i don't think the current version support perturbing soil variables in from the campaign translator. you can only change things in the X file i think. you can of course have SOIL.SOL files with arbitrarily many soil profiles in them which vary anything you want and then vary the SOIL_ID parameter in the campaign file in order to reference those different profiles in the simulations. you aren't limited to putting just one soil profile in each soil.json file. 

hopefully the next psims release will support more general parameter variation including varying arbitrary things in the soil and cultivar files.
