### ISSUE TITLE
Planting date for DSSAT experiments

### ISSUE THREAD

**Issue by schmidtfederico** [RDCEP/psims#4]
Hello,

I'm trying to recreate an experiment a researcher in my team runs periodically on his standalone DSSAT installation. In this experiment, he specifies the crop's planting date (PDATE) in the "Planting Details" section of the DSSAT experiment.
However, I've noticed that in the example found in the GitHub repo the planting date is specified in the "Automatic Management" section by using the "pfday" variable in the master campaign file.

Since we need to use the Planting Details section, I tried to modify the PDATE variable by creating the variable 'pdate' in the NetCDF file, but there's part of the code that formats it in a way DSSAT can't use: for instance, '12-Jul'. A comment states that it's an special case for APSIM.

``` python
# SPECIAL CASE FOR APSIM!
# CHANGE EDATE TO PDATE - 30 days
# CHANGE RESET DATE TO PDATE - 60 days
if var == 'pdate': eday = int(round(val_old)) - 30
    if eday < 1: eday = 365 + eday # non-leap year
        rday = int(round(val_old)) - 60
    if rday < 1:
        rday = 365 + rday # non-leap year
    edate = (dt.date(1900, 1, 1) + dt.timedelta(eday - 1)).strftime('%e-%b')
    rdate = (dt.date(1900, 1, 1) + dt.timedelta(rday - 1)).strftime('%e-%b')
    dict_replace(exp['experiments'][j], 'edate', str(edate), occ = occ)
    print("Rdate: %s" % rdate)
    dict_replace(exp['experiments'][j], 'date', str(rdate), occ = occ)
```

Furthermore, I noticed that the planting date in the experiment.json was called just 'date' and that the 'event' property defined in which part of the DSSAT experiment file that date should be used, so I tried creating the variable 'date' in the NetCDF and, though I was able to overwrite the PDATE variable, I ended overwriting every 'date' field in the experiment.

``` javascript
"management": {
    "events": [
      {
        ...,
        "date": "...",
        "event": "planting"
      },
     ...,
      {
        "date": "...",
        "event": "irrigation"
      },
      {
        "date": "...",
        "event": "harvest"
      }
    ]
  }
```

Is there a way to change only the PDATE field in a DSSAT experiment? And how about the others dates (HDATE and IDATE), can they be overwritten by using the master campaign file?

Greetings and thanks for your help.
Federico.

**Comment by joshuaelliott** [comment]
yeah, its not very elegant at the moment but here's the current approach. 

we want to make the camp2json script as generic as possible and so chose to make it so that you could put any variable name in the Campaign.nc4 file and if it was found in the json template file it would replace it with the given value. for names that appear twice such as "date" in the different event sections, you have to specify which appearance (in order of the file) you want to replace or else it will replace all of them. you do this by including an _N on the variable name. so for planting date, you would call the variable in the Campaign.nc4 file date_1. definitely not the most elegant solution but in the prototyping stage thus far our goal has been to keep things as generic as possible to make it easier to add news models to the platform. 

also the example in git is for an automatic planting window which is why it refers to pfday and plday. these don't map directly to dssat variables but instead are combined with the pfyear and plyear or something like that to create the automatic planting window parameters. if you need to do a fixed planting then you also need to change the planting parameter in the management options from A to M. 

have you created a fork of the repo on git? if you want to propose changes to the translator scripts or data formats to do this in a more elegant way, you should fork the repo and make some changes!

cheers,
joshua

**Comment by schmidtfederico** [comment]
Dear Joshua,

Thank you very much for your help. By following your advice I was able to create a Campaign.nc4 that overwrites each of the dates we need to change, plus, the same trick worked for other variables too, such as the fertilizer amount.

We still aren't able to overwrite the soil initial conditions, as I posted in another issue, but troubleshooting this allows us to start testing pSIMS with some minor experiments. You may mark this issue as resolved now. :)

Greetings,
Federico.
