### ISSUE TITLE
DSSAT Summary file parsing

### ISSUE THREAD

**Issue by schmidtfederico** [RDCEP/psims#7]
Hello,

I've noticed while creating a new postprocess hook for DSSAT summary files that there's a section in the original hook (`OUT2psims.py` between lines 184 and 199) that checks for asterisks and other special values and replaces them with -99; are these valid DSSAT output values? I'm asking because I've created a MongoDB postprocess hook that I'm using in our projects and this came as a surprise to me and my colleagues.

Please let me know if this is correct so I can change my hook to include those special cases. After checking it, I can create a pull request for you to be able to merge it into your pSIMS version if your team is interested in adding it to the main branch.

Greetings,
Federico.

**Comment by joshuaelliott** [comment]
for some crops/variables, dssat does indeed occasionally output sequences of \* instead of values. i think it mostly occurs for date variables where it outputs something like ******\* instead of a typical YYYYDDD date like 1988025. i think we asked the dssat folks at some point what this meant and they told us it was some kind of failed out that was equivalent to when dssat prints -99. so for simplicity, we scan for all such special non-numeric values and replace them with -99.

**Comment by schmidtfederico** [comment]
Great, thank you very much for the information! I'll add it to the hook's code.
